repos:
  - repo: local
    hooks:
      - id: format
        name: ruff format
        entry: pdm run format
        language: system
        pass_filenames: false
        always_run: true
        require_serial: true
      - id: lint
        name: ruff lint
        entry: pdm run lint
        language: system
        pass_filenames: false
        always_run: true
        require_serial: true
      - id: typecheck
        name: mypy typecheck
        entry: pdm run typecheck
        language: system
        pass_filenames: false
        always_run: true
        require_serial: true
      - id: test-coverage
        name: pytest test coverage
        entry: pdm run coverage
        language: system
        pass_filenames: false
        always_run: true
        require_serial: true

